# Generated by Django 4.1 on 2022-08-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_order_client_alter_client_user'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='adress',
        ),
        migrations.AddField(
            model_name='bottle',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='bottles', to='clients.order', verbose_name='Заказы'),
        ),
    ]
