# Generated by Django 4.1 on 2022-08-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_order_client_alter_client_user'),
        ('core', '0002_remove_bottle_adress_bottle_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottlesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bottle')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.order')),
            ],
        ),
    ]
