# Generated by Django 4.1 on 2022-08-25 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_bottle_orders_bottlescount_created_at2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottlescount',
            name='created_at2',
        ),
        migrations.RemoveField(
            model_name='bottlescount',
            name='updated_at2',
        ),
        migrations.AlterField(
            model_name='bottlescount',
            name='bottle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bottle'),
        ),
    ]
