# Generated by Django 4.1 on 2022-08-25 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_bottlescount_created_at2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottlescount',
            name='bottle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottle', to='core.bottle'),
        ),
    ]
