# Generated by Django 4.1 on 2022-08-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный покупатель')),
                ('botlle', models.IntegerField(default=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Фото')),
            ],
        ),
    ]
