# Generated by Django 4.1 on 2022-09-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_order_client_alter_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contacts',
            field=models.CharField(help_text='Номер или соц. сеть', max_length=255),
        ),
    ]
